name: Build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache west modules
        uses: actions/cache@v4
        with:
          path: |
            modules
            zephyr
            bootloader
          key: ${{ runner.os }}-build-${{ hashFiles('**/west.yml') }}
      - name: Install West and Build
        uses: zmkfirmware/zmk-action-setup@v1
      - name: Build ZMK
        run: |
          west build -s app -b nice_nano_v2 -- -DSHIELD=sofle_left
          cp build/zephyr/zmk.uf2 sofle_left.uf2
          west build -p -s app -b nice_nano_v2 -- -DSHIELD=sofle_right
          cp build/zephyr/zmk.uf2 sofle_right.uf2
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: "*.uf2"
